
package r6scriptz;
import java.awt.event.KeyEvent;
import java.io.*;
import java.nio.charset.Charset;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author wan
 */
public class App extends javax.swing.JFrame {
    static String start = "z";
    static String end = "m";
    /**
     * Creates new form NewJFrame
     */
    public App() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jTextArea1 = new javax.swing.JTextArea();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 24)); // NOI18N
        jButton1.setText("Start program!");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 260, 40));

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 24)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("Start Key");
        jTextArea1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTextArea1MousePressed(evt);
            }
        });
        getContentPane().add(jTextArea1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 150, 40));

        jTextArea2.setEditable(false);
        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 24)); // NOI18N
        jTextArea2.setRows(5);
        jTextArea2.setText("End Key\n");
        jTextArea2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTextArea2MousePressed(evt);
            }
        });
        getContentPane().add(jTextArea2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 110, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/r6scriptz/Project.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 510));
        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextArea1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextArea1MousePressed
        jTextArea1.setText("...");
        jTextArea1.addKeyListener(new java.awt.event.KeyListener(){
            @Override
            public void keyTyped(KeyEvent e) {
            }

            @Override
            public void keyPressed(KeyEvent e) {
                jTextArea1.setText(String.valueOf(e.getKeyChar()));
                start = String.valueOf(e.getKeyChar());
            }

            @Override
            public void keyReleased(KeyEvent e) {
                
            }
            
        });
    }//GEN-LAST:event_jTextArea1MousePressed

    private void jTextArea2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextArea2MousePressed
          jTextArea2.setText("...");
        jTextArea2.addKeyListener(new java.awt.event.KeyListener(){
            @Override
            public void keyTyped(KeyEvent e) {
            }

            @Override
            public void keyPressed(KeyEvent e) {
                jTextArea2.setText(String.valueOf(e.getKeyChar()));
                end = String.valueOf(e.getKeyChar());
            }

            @Override
            public void keyReleased(KeyEvent e) {
                
            }
            
        });
    }//GEN-LAST:event_jTextArea2MousePressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JOptionPane.showMessageDialog(null,"To end the program just press the end key! (default is a)");
        File config = new File("config.txt");
        FileOutputStream fileOutput = null;
        try {
            fileOutput = new FileOutputStream(config);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
        }
        DataOutputStream outputStream = new DataOutputStream(fileOutput);
        try {
            outputStream.write(start.getBytes(Charset.forName("UTF-8")));
            outputStream.write(("\n"+end).getBytes(Charset.forName("UTF-8")));
        } catch (IOException ex) {
            Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
        }
        JOptionPane.showMessageDialog(null,"Config file created at: " + config.getAbsolutePath() +"\nUr hotkeys are: "+
                "\nStart: " + start + "\nEnd: " + end +"\nIMPORTANT: You might need to spam the end key\nsince its not really responsive in this script"
                        + "\nI'll eventually find out how to fix it lmao");
        try{      
            JOptionPane.showMessageDialog(null,"This program requires python3.10 to run.\nPlease be sure you got the latest version to run it");
            ProcessBuilder builder = new ProcessBuilder("python3",System.getProperty("user.dir") + "\\main.py");
            System.out.println("python3 " +System.getProperty("user.dir"));
            Process process = builder.start();
            System.out.println("hola");
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Error!, do u have python installed?");
        }
        System.out.println("debug");
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new App().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    // End of variables declaration//GEN-END:variables
}
